---
apiVersion: v1
kind: Namespace
metadata:
  name: challenge2

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: challenge2
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
