apiVersion: batch/v1
kind: Job
metadata:
  name: backup-job
spec:
  template:
    metadata:
      name: backup-job
    spec:
      restartPolicy: Never
      containers:
      - name: backup-restore
        image: mariadb
        command:
        - sh
        - -c
        - |
          until mysqladmin ping -h mariadb-service -u root -p$MARIADB_ROOT_PASSWORD --silent; do
            echo "Waiting for MariaDB to start..."
            sleep 5
          done
          apt update -y && apt install -y curl
          curl -L -o mediawiki.sql "https://drive.google.com/uc?export=download&id=1pnan6QBDVM4MsRVJC3KRZvfBBiDGAgOj"
          mysql -h mariadb-service -u root -p $MARIADB_ROOT_PASSWORD < mediawiki.sql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password

  backoffLimit: 4
