apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      initContainers:
      - name: init-restore-db
        image: busybox
        command: ["/bin/sh", "-c", "curl -L -o /var/lib/mysql/database.sql https://drive.google.com/file/d/<file-id>/view?usp=sharing"]
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysqladmin ping --silent'
      securityContext:
        runAsUser: 999
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
