apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      - name: backup-restore
        image: mariadb:10.5
        command:
        - sh
        - -c
        - |
          apk add --no-cache curl
          until mysqladmin ping -h localhost --silent; do
            echo "Waiting for MariaDB to start..."
            sleep 5
          done
          curl -L -o mediawiki.sql  "https://drive.google.com/uc?export=download&id=1pnan6QBDVM4MsRVJC3KRZvfBBiDGAgOj"
          mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD < mediawiki.sql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      resources:
        requests:
          storage: 1Gi